blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blogpost_list/', cache_page(60)(BlogPostListView.as_view()), name='blogpost_list'),
    path('create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('post/<slug:slug>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('edit/<slug:slug>', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('delete/<slug:slug>', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import MailingServiceListView, MailCreateView, MailDetailView, MailUpdateView, MailDeleteView, \
    ClientsListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, LogsListView, \
    toggle_mailing_activity

app_name = 'mailing'

urlpatterns = [
    path('', MailingServiceListView.as_view(), name='index'),
    path('mailing/', MailingServiceListView.as_view(), name='mail_list'),
    path('create_mailing/', MailCreateView.as_view(), name='create_mailing'),
    path('mailing/<int:pk>/', MailDetailView.as_view(), name='mail_detail'),
    path('mailing/<int:pk>/update/', MailUpdateView.as_view(), name='mail_update'),
    path('mailing/<int:pk>/delete/', MailDeleteView.as_view(), name='mail_delete'),
    path('clients/', ClientsListView.as_view(), name='clients'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('logs/', LogsListView.as_view(), name='logs'),
    path('mailing/toggle-activity/<int:pk>/', toggle_mailing_activity, name='toggle_mailing_activity'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import RegisterView, VerifyEmailView, UsersView, toggle_user_activity

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('verify_email/<str:uid>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('users/', UsersView.as_view(), name='users_list'),
    path('toggle_user_activity/<int:user_id>/', toggle_user_activity, name='toggle_user_activity'),
]

mailing/models.py
from django.db import models
from django.contrib.auth import get_user_model

NULLABLE = {'blank': True, 'null': True}

User = get_user_model()


class Client(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя', unique=True)
    email = models.EmailField(max_length=100, verbose_name='Email', unique=True)
    comment = models.TextField(verbose_name='Комментарий')
    creator = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='clients_created')

    def __str__(self):
        return f'{self.name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingService(models.Model):
    daily = 'Раз в день'
    weekly = 'Раз в неделю'
    monthly = 'Раз в месяц'

    choices = (
        (daily, 'Раз в день'),
        (weekly, 'Раз в неделю'),
        (monthly, 'Раз в месяц')
    )

    created = 'Создана'
    started = 'Рассылка запущена'
    finished = 'Рассылка завершена'

    status_choices = (
        (created, 'Создана'),
        (started, 'Рассылка запущена'),
        (finished, 'Рассылка завершена'),
    )

    start_time = models.DateTimeField(verbose_name='Начало рассылки')
    end_time = models.DateTimeField(verbose_name='Окончание рассылки', null=True)
    status = models.CharField(max_length=50, choices=status_choices, default=created, verbose_name='Статус')
    mailing_period = models.CharField(max_length=50, choices=choices, default=daily, verbose_name='Период рассылки')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    creator = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='mailings_created')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.start_time} - {self.end_time}. Статус: {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            ('set_active', 'Can set mailing active'),
        ]


class Message(models.Model):
    text = models.TextField(verbose_name='Текст сообщения', **NULLABLE)
    title = models.CharField(max_length=100, verbose_name='Тема письма')
    mailing = models.ForeignKey(MailingService, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Logs(models.Model):
    last_try = models.DateTimeField(verbose_name='Последняя попытка', auto_now_add=True)
    status = models.CharField(max_length=50, verbose_name='Статус')
    server_response = models.TextField(verbose_name='Ответ сервера', **NULLABLE)

    mailing = models.ForeignKey(MailingService, on_delete=models.CASCADE, verbose_name='Рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент', **NULLABLE)

    def __str__(self):
        return f'{self.last_try} - {self.status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms
from .models import MailingService, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingServiceForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingService
        fields = '__all__'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

mailing/views.py
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from .models import Client, Logs, Message, MailingService
from .forms import MailingServiceForm, ClientForm, MessageForm
from django.views.generic import ListView
from blog.models import BlogPost


class MailingServiceListView(ListView):
    template_name = 'mailing/index.html'
    context_object_name = 'mailing_list'

    def get_queryset(self):
        return MailingService.objects.all()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['all'] = context_data['object_list'].count()
        context_data['active'] = context_data['object_list'].filter(status=MailingService.started).count()

        mailing_list = context_data['object_list'].prefetch_related('clients')
        clients = set()
        [[clients.add(client.email) for client in mailing.clients.all()] for mailing in mailing_list]
        context_data['clients_count'] = len(clients)

        random_posts = BlogPost.objects.order_by('?')[:3]
        context_data['random_posts'] = random_posts

        return context_data


class MailCreateView(LoginRequiredMixin, CreateView):
    model = MailingService
    form_class = MailingServiceForm
    template_name = 'mailing/mail_form.html'
    success_url = reverse_lazy('mailing:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(MailingService, Message, extra=1, form=MessageForm)

        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mailing:mail_detail', args=[self.object.pk])


class MailDetailView(LoginRequiredMixin, DetailView):
    model = MailingService
    template_name = 'mailing/mail_detail.html'
    permission_required = 'mailing.view_mail'


class MailUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = MailingService
    form_class = MailingServiceForm
    template_name = 'mailing/mail_form.html'
    success_url = reverse_lazy('mailing:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(MailingService, Message, extra=1, form=MessageForm)

        if hasattr(self, 'object') and self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def test_func(self):
        mailing = self.get_object()
        return self.request.user == mailing.creator

    def handle_no_permission(self):
        raise PermissionDenied("You don't have permission to edit this mailing.")


class MailDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingService
    template_name = 'mailing/mail_confirm_delete.html'
    success_url = reverse_lazy('mailing:index')


class ClientsListView(ListView):
    model = Client
    template_name = 'mailing/client_list.html'


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailing:clients')


class ClientDetailView(DetailView):
    model = Client
    template_name = 'mailing/client_detail.html'


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailing:clients')


class ClientDeleteView(DeleteView):
    model = Client
    template_name = 'mailing/client_confirm_delete.html'
    success_url = reverse_lazy('mailing:clients')


class LogsListView(ListView):
    model = Logs
    template_name = 'mailing/log_list.html'


@login_required
@permission_required('mailing.set_active', raise_exception=True)
def toggle_mailing_activity(request, pk):
    mailing = get_object_or_404(MailingService, pk=pk)
    mailing.is_active = not mailing.is_active
    mailing.save()
    return HttpResponseRedirect(reverse('mailing:index'))

mailing/templates/mailing/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Главная страница{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>

<header class="bg-dark text-white p-4">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <a href="{% url 'mailing:index' %}" class="text-white text-decoration-none">
                <strong>My Mailing Service</strong>
            </a>
            <nav class="nav">
                {% if request.user.is_authenticated %}
                <a class="nav-link text-white" href="{% url 'users:users_list' %}">Пользователи</a>
                <a class="nav-link text-white" href="{% url 'blog:blogpost_list' %}">Блог</a>
                <a class="nav-link text-white" href="{% url 'mailing:clients' %}">Клиенты</a>
                <a class="nav-link text-white" href="{% url 'mailing:logs' %}">Журнал рассылок</a>
                <span class="nav-link text-white">{{ request.user.email }}</span>
                {% endif %}
                {% if not request.user.is_authenticated %}
                <a class="nav-link text-white" href="{% url 'users:login' %}">Вход</a>
                <a class="nav-link text-white" href="{% url 'users:register' %}">Регистрация</a>
                {% else %}
                <form method="post" action="{% url 'users:logout' %}" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link text-white nav-link">Выход</button>
                </form>
                {% endif %}
            </nav>
        </div>
    </div>
</header>

{% block content %}{% endblock %}

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block title %}Подтверждение удаления клиента{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">Подтверждение удаления клиента</h2>
        <p>Вы уверены, что хотите удалить клиента "{{object.name}}"?</p>
        <form method="post" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Да, удалить</button>
        </form>
        <a href="{% url 'mailing:clients' %}" class="btn btn-secondary">Отмена</a>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}
{% block title %}Просмотр клиента{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">Просмотр клиента</h2>
        <dl class="row">
            <dt class="col-sm-3">Имя:</dt>
            <dd class="col-sm-9">{{ object.name }}</dd>
            
            <dt class="col-sm-3">Email:</dt>
            <dd class="col-sm-9">{{ object.email }}</dd>
            
            <dt class="col-sm-3">Комментарий:</dt>
            <dd class="col-sm-9">{{ object.comment }}</dd>
            
            <div class="col-sm-12 mt-4">
                <a href="{% url 'mailing:client_update' pk=object.pk %}" class="btn btn-primary">Редактировать</a>
            </div>
        </dl>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}
{% block title %}Форма клиента{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">Форма клиента</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block title %}Список клиентов{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">Список клиентов</h2>

        <ul class="list-group">
            {% for client in object_list %}
                <li class="list-group-item">
                        {{ client.name }}
                    {% if client.creator == user or user.is_superuser %}
                        <a href="{% url 'mailing:client_update' pk=client.pk %}" class="btn btn-sm btn-primary ml-2">Редактировать</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        <a href="{% url 'mailing:create_client' %}" class="btn btn-primary mt-3">Добавить клиента</a>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/distibution_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
  <h2>Distribution Details</h2>
  <p>Start Time: {{ distribution.start_time }}</p>
  <p>End Time: {{ distribution.end_time }}</p>
  <p>Frequency: {{ distribution.frequency }}</p>
{% endblock %}

mailing/templates/mailing/distribution_list.html
{% extends 'mailing/base.html' %}

{% block content %}
  <h2>Distributions</h2>
  <ul>
    {% for distribution in object_list %}
      <li><a href="{% url 'mailing:distribution_detail' distribution.pk %}">{{ distribution.start_time }} - {{ distribution.end_time }}: {{ distribution.frequency }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}

{% block title %}Домашняя страница{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Статистика рассылок</h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Количество рассылок всего</th>
                                <th>Количество активных рассылок</th>
                                <th>Количество уникальных клиентов</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ all }}</td>
                                <td>{{ active }}</td>
                                <td>{{ clients_count }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Случайные статьи из блога</h3>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        {% for post in random_posts %}
                        <li class="list-group-item"><a href="{% url 'blog:blogpost_detail' post.slug %}">{{ post.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Рассылки</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Время рассылки</th>
                                    <th>Статус рассылки</th>
                                    <th>Периодичность рассылки</th>
                                    <th>Подробности рассылки</th>
                                    <th>Редактирование рассылки</th>
                                    <th>Удаление рассылки</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for object in object_list %}
                                <tr>
                                    <td>{{ object.start_time }}</td>
                                    <td>{{ object.status }}</td>
                                    <td>{{ object.period }}</td>
                                    <td>
                                        {% if request.user.is_authenticated %}
                                        <a href="{% url 'mailing:mail_detail' object.pk %}" class="btn btn-primary btn-sm">Полная
                                            информация</a>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if object.creator == user or user.is_superuser %}
                                        <a href="{% url 'mailing:mail_update' object.pk %}" class="btn btn-warning btn-sm">Исправить</a>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if object.creator == user or user.is_superuser %}
                                        <a href="{% url 'mailing:mail_delete' object.pk %}" class="btn btn-danger btn-sm">Удалить</a>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if perms.mailing.set_active or user.is_superuser %}
                                        <form method="post" action="{% url 'mailing:toggle_mailing_activity' object.pk %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-secondary btn-sm">
                                                {% if object.is_active %}
                                                Деактивировать
                                                {% else %}
                                                Активировать
                                                {% endif %}
                                            </button>
                                        </form>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12 text-center">
            <a href="{% url 'mailing:create_mailing' %}" class="btn btn-primary">Создать рассылку</a>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html' %}
{% block title %}Список логов{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">Список логов</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Дата последней попытки</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Ответ сервера</th>
                </tr>
            </thead>
            <tbody>
                {% for log in object_list %}
                    <tr>
                        <td>{{ log.last_try }}</td>
                        <td>{{ log.status }}</td>
                        <td>{{ log.server_response }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/mail_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block title %}Подтверждение удаления рассылки{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">Подтверждение удаления рассылки</h2>
        <p>Вы уверены, что хотите удалить рассылку "{{object.title}}"?</p>
        <form method="post" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Да, удалить</button>
        </form>
        <a href="{% url 'mailing:index' %}" class="btn btn-secondary">Отмена</a>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/mail_detail.html
{% extends 'mailing/base.html' %}
{% block title %}Просмотр рассылки{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">Просмотр рассылки</h2>
        <dl class="row">
            <dt class="col-sm-3">Начало рассылки:</dt>
            <dd class="col-sm-9">{{ object.start_time }}</dd>

            <dt class="col-sm-3">Окончание рассылки:</dt>
            <dd class="col-sm-9">{{ object.end_time }}</dd>

            <dt class="col-sm-3">Период рассылки:</dt>
            <dd class="col-sm-9">{{ object.get_mailing_period_display }}</dd>

            <dt class="col-sm-3">Статус:</dt>
            <dd class="col-sm-9">{{ object.get_status_display }}</dd>

            <div class="col-sm-12 mt-4">
                <a href="{% url 'mailing:mail_update' pk=object.pk %}" class="btn btn-primary">Редактировать</a>
            </div>
        </dl>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/mail_form.html
{% extends 'mailing/base.html' %}
{% block title %}
    {% if form.instance.pk %}Редактирование рассылки{% else %}Создание рассылки{% endif %}
{% endblock %}

{% block content %}
<main role="main">
    <div class="container">
        <h2 class="mt-4 mb-4">
            {% if form.instance.pk %}Редактирование рассылки{% else %}Создание рассылки{% endif %}
        </h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            {% if formset %}
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form.as_p }}
                {% endfor %}
            {% endif %}

            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/mail_list.html
{% extends 'mailing\base.html' %}
{% block content %}
<main role="main">
    <div class="container mt-4">
        <h2 class="mb-4">Рассылки</h2>
        <div class="row mb-4">
            {% if request.user.is_authenticated %}
            <div class="col">
                <a href="{% url 'mailing:create_mailing' %}" class="btn btn-primary">Добавить рассылку</a>
            </div>
            {% endif %}
        </div>
        <div class="list-group">

            {% for mail in object_list %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                    <span>{{ mail.id }}. {{ mail.start_time }} - {{ mail.end_time }}. Статус: {{ mail.status }}</span>
                    {% if mail.creator == user %}
                    <a href="{% url 'mailing:mail_update' pk=mail.pk %}" class="btn btn-sm btn-primary ml-2">Редактировать</a>
                    {% endif %}
                </div>

            </li>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block title %}Message List{% endblock %}

{% block content %}
    <h1>Message List</h1>
{% endblock %}