blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blogpost_list/', cache_page(60)(BlogPostListView.as_view()), name='blogpost_list'),
    path('create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('post/<slug:slug>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('edit/<slug:slug>', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('delete/<slug:slug>', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify

NULLABLE = {'blank': True, 'null': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=300, verbose_name='title')
    slug = models.CharField(max_length=300, **NULLABLE, verbose_name='slug')
    content = models.TextField(verbose_name='content')
    preview = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='preview')
    date_created = models.DateField(auto_now_add=True, verbose_name='date_created')
    view_count = models.IntegerField(default=0, verbose_name='view_count')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

blog/views.py
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import BlogPost
from django.urls import reverse_lazy


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blog/blogpost_list.html'
    context_object_name = 'posts'


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/blogpost_detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogPostCreateView(CreateView):
    model = BlogPost
    template_name = 'blog/blogpost_form.html'
    fields = ['title', 'slug', 'content', 'preview']
    success_url = reverse_lazy('blog:blogpost_list')

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        if form.instance.slug in BlogPost.objects.values_list('slug', flat=True):
            form.add_error('title', 'Такой slug уже существует')
            return self.form_invalid(form)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:blogpost_list')


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    template_name = 'blog/blogpost_form.html'
    fields = ['title', 'content', 'slug', 'preview']

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:blogpost_list')


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = 'blog/blogpost_confirm_delete.html'
    success_url = reverse_lazy('blog:blogpost_list')

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
  <h2>Confirm Delete</h2>
  <p>Are you sure you want to delete "{{ post.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a href="{% url 'blog:blogpost_list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'mailing/base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h2 class="card-title">{{ post.title }}</h2>
        <p class="card-text">{{ post.content }}</p>
        <p class="card-text">Date Created: {{ post.date_created }}</p>
        <p class="card-text">Views: {{ post.view_count }}</p>
        {% if post.preview %}
        <img src="{{ post.preview.url }}" alt="{{ post.title }}" class="card-img-top img-fluid"
             style="max-width: 10%; height: auto;">
        {% endif %}

        {% if request.user.is_authenticated %}
        <a href="{% url 'blog:blogpost_update' post.slug %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'blog:blogpost_delete' post.slug %}" class="btn btn-danger">Delete</a>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'mailing/base.html' %}

{% block title %}Create/Edit Blog Post{% endblock %}

{% block content %}
  <h2>Create/Edit Blog Post</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'mailing/base.html' %}

{% block title %}Blog Posts{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Посты блога</h2>
    <a href="{% url 'blog:blogpost_create' %}" class="btn btn-success mb-3">Добавить пост</a>

    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 mb-4">
            <div class="card">
                {% if post.preview %}
                <img src="{{ post.preview.url }}" class="card-img-top" alt="{{ post.title }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'blog:blogpost_detail' post.slug %}">{{ post.title }}</a>
                    </h5>
                    <p class="card-text">{{ post.content }}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Опубликовано: {{ post.date_created }}</small>
                </div>
            </div>
        </div>

        {% if forloop.counter|divisibleby:3 and not forloop.last %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}