blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blogpost_list/', cache_page(60)(BlogPostListView.as_view()), name='blogpost_list'),
    path('create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('post/<slug:slug>/', BlogPostDetailView.as_view(), name='blogpost_detail'),
    path('edit/<slug:slug>', BlogPostUpdateView.as_view(), name='blogpost_update'),
    path('delete/<slug:slug>', BlogPostDeleteView.as_view(), name='blogpost_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import RegisterView, VerifyEmailView, UsersView, toggle_user_activity

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('verify_email/<str:uid>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('users/', UsersView.as_view(), name='users_list'),
    path('toggle_user_activity/<int:user_id>/', toggle_user_activity, name='toggle_user_activity'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    email_token = models.CharField(max_length=50, **NULLABLE, verbose_name='email_token')
    clients = models.ManyToManyField('mailing.Client', verbose_name='Клиенты', **NULLABLE)
    mails = models.ManyToManyField('mailing.MailingService', related_name='users', verbose_name='Рассылки', **NULLABLE)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        permissions = [
            ('set_active', 'Can set user active'),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User


class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import string
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.views import View
from django.views.generic import CreateView, UpdateView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from users.forms import UserSignupForm, UserProfileForm
from users.models import User
from django.contrib import messages

User = get_user_model()


class RegisterView(CreateView):
    model = User
    form_class = UserSignupForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        token = ''.join(random.choices(string.ascii_letters + string.digits, k=50))
        new_user.email_token = token
        new_user.save()

        verification_link = self.request.build_absolute_uri(
            reverse('users:verify_email', kwargs={'uid': new_user.pk, 'token': token}))

        subject = 'Подтверждение регистрации'
        message = render_to_string('users/registration_email.html', {'verification_link': verification_link})
        plain_message = strip_tags(message)
        sender_email = settings.EMAIL_HOST_USER
        recipient_email = new_user.email
        send_mail(subject, plain_message, sender_email, [recipient_email], html_message=message)

        # Добавление сообщения о регистрации
        messages.success(self.request,
                         'Регистрация прошла успешно. Пожалуйста, проверьте свою почту для завершения регистрации.')

        return super().form_valid(form)


class VerifyEmailView(View):
    def get(self, request, uid, token):
        user = get_object_or_404(User, pk=uid, email_token=token)
        user.is_active = True
        user.save()
        return render(request, 'users/registration_success.html')


class ProfileView(LoginRequiredMixin, View):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'

    def get(self, request):
        return render(request, self.template_name, {'user': request.user})


class ProfileEditView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/profile_edit.html'

    def get_object(self, queryset=None):
        if self.request.user.is_authenticated:
            return self.request.user
        return None

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:profile')


class UsersView(LoginRequiredMixin, PermissionRequiredMixin, View):
    model = User
    permission_required = 'users.view_user'
    template_name = 'users/users_list.html'

    def get(self, request):
        users = User.objects.all()
        return render(request, self.template_name, {'users': users})


@permission_required('users.set_active')
def toggle_user_activity(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.is_active = not user.is_active
    user.save()
    return redirect('users:users_list')

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block title %}Авторизация{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Login</h2>
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary btn-block mt-4">Login</button>
            </form>
          </div>
        </div>
        <p class="text-center mt-3">
          Ещё нет аккаунта? <a href="{% url 'users:register' %}">Регистрация</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Register</h2>
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary btn-block mt-4">Регистрация</button>
            </form>
          </div>
        </div>
        <p class="text-center mt-3">
          Уже есть аккаунт? <a href="{% url 'users:login' %}">Login</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/registration_email.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтверждение регистрации</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <h2>Поздравляем!</h2>
    <p>Вы успешно зарегистрировались на нашем портале.</p>
    <p>Для завершения регистрации и активации вашей учетной записи, пожалуйста, перейдите по следующей ссылке:</p>
    <p><a href="{{ verification_link }}">Подтвердить регистрацию</a></p>
    <p>Если вы не регистрировались на нашем портале, просто проигнорируйте это письмо.</p>
    <p>С уважением,</p>
    <p>Администрация портала</p>
</body>
</html>

users/templates/users/registration_success.html
{% extends 'mailing/base.html' %}

{% block title %}Registration Success{% endblock %}

{% block content %}
  <h2>Registration Successful</h2>
  <p>Thank you for registering. Please check your email to verify your account.</p>
  <p><a href="{% url 'users:login' %}">Login</a></p>
{% endblock %}

users/templates/users/users_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<main role="main">
    <div class="container mt-4">
        <h2 class="mb-4">Пользователи</h2>

        <div class="list-group">
            {% for user in users %}
            <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                    <span class="font-weight-bold">{{ user.email }}</span>
                    {% if user.is_active %}
                    <span class="badge badge-success">Активен</span>
                    {% else %}
                    <span class="badge badge-danger">Не активен</span>
                    {% endif %}
                    {% if perms.users.set_active %}
                    <div>
                        <form method="post" action="{% url 'users:toggle_user_activity' user.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">
                                {% if user.is_active %}
                                Деактивировать
                                {% else %}
                                Активировать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                    {% endif %}
                </div>
            </li>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}